apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-tools
  namespace: default    # Change namespace if desired
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-tools
  template:
    metadata:
      labels:
        app: debug-tools
    spec:
      containers:
      - name: debug-tools
        image: docker.io/kunal0137/debug-tools:latest
        imagePullPolicy: IfNotPresent
        # Uncomment below if you want to run as a specific user/group
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Container will stay alive and ready for exec
        command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: debug-tools
  namespace: default   # Change namespace if desired
spec:
  selector:
    app: debug-tools
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
